name: iOS Deployment

on:
  push:
    branches:
      - main  # Adjust this to your main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # Adjust to the version you need

      - name: Install Bundler
        run: gem install bundler

      - name: Install Dependencies
        run: |
          cd ios  # Navigate to the directory containing the Gemfile
          bundle install

      - name: Update Fastlane
        run: gem install fastlane

      - name: Verify Fastlane Version
        run: |
          cd ios
          bundle exec fastlane --version  # Ensure Fastlane is installed and working

      - name: Run Deployment Script
        run: |
          chmod +x ci_script.sh
          ./ci_script.sh

      - name: Print Fastlane Gym Log
        if: failure()
        run: cat ios/output/gym_output.log
