name: iOS Deployment

on:
  push:
    branches:
      - main  # Adjust this to your main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # Adjust to the version you need

      - name: Install dependencies
        run: |
          gem install bundler
          cd ios  # Navigate to the directory containing the Gemfile
          bundle install

      - name: Install Fastlane
        run: |
          gem install fastlane
          cd ios
          bundle exec fastlane --version  # Ensures Fastlane is installed and working

      - name: Run deployment script
        run: |
          chmod +x ci_script.sh
          ./ci_script.sh
