name: iOS Deployment

on:
  push:
    branches:
      - main  # Adjust this to your main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0  # Adjust to the version you need

      - name: Install dependencies
        run: |
          gem install bundler
          cd ios  # Navigate to the directory containing the Gemfile
          bundle install

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode_13.4.1.app  # Adjust to the Xcode version you need

      - name: Install CocoaPods
        run: |
          cd ios  # Navigate to the directory containing the Podfile
          bundle exec pod install --repo-update

      - name: Run deployment script
        run: |
          cd ios  # Navigate to the directory containing the deployment script
          ./ci_script.sh
