name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: |
        cd ios
        bundle install

    - name: Install Fastlane
      run: gem install fastlane

    - name: Set up Xcode
      run: |
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -license accept

    - name: Run CI Script
      run: |
        chmod +x ./ci_script.sh
        ./ci_script.sh

    - name: Build and Test with Xcode
      run: |
        xcodebuild -workspace firstApp.xcworkspace \
                    -scheme firstApp \
                    -sdk iphonesimulator \
                    -destination 'platform=iOS Simulator,name=iPhone 14' \
                    build test | xcpretty

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-build
        path: ios/build

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: ios-test-results
        path: ios/build/reports
